config/routes.rb
NeighborsMaps::Application.routes.draw do
  resources :ol3_vector_styles
  resources :vector_features

  root 'welcome#index'
  get 'welcome/write_project_markdown' => 'welcome#write_project_markdown'
  resources :theme_map_layers
  resources :map_layers
  
  resources :theme_maps do
    get 'revert_geo_db', on: :member
    post 'update_geo_db', on: :member
    post 'delete_feature', on: :member
  end

  resources :theme_maps
  get 'theme_maps/:name' => 'theme_maps#show'

  resources :forums
  resources :wiki
  resources :about
  resources :guide
  resources :welcome 
  resources :administrators  
  
  

  resources :walk_surveys
  resources :overall_map
  resources :half_blocks
  resources :neighbors
  resources :greenwood_users
  resources :maps

  get '/logout' =>  'sessions#destroy'
  get '/login' => 'sessions#new'
  get '/register'=> 'users#create'
  get '/signup' => 'users#new'
  get '/activate/:activation_code' =>  'users#activate', :activation_code => nil

  resources :users
  resource :session
  resources :passwords
  resources :users

  get '/change_password' => 'users#change_password'
  get  '/neighbors/:search_column/:match_list' => 'neighbors#index'

end

app/views/theme_maps_layers/show.html.erb
<p>
  <b>Theme maps:</b>
  <%=h @theme_map_layer.theme_maps_id %>
</p>

<p>
  <b>Map layer:</b>
  <%=h @theme_map_layer.map_layer_id %>
</p>

<p>
  <b>Line color:</b>
  <%=h @theme_map_layer.line_color %>
</p>

<p>
  <b>Fill color:</b>
  <%=h @theme_map_layer.fill_color %>
</p>



<%= link_to 'Edit', edit_theme_map_layer_path(@theme_map_layer) %> |
<%= link_to 'Back', theme_map_layers_path %>