config/routes.rb
NeighborsMaps::Application.routes.draw do
  resources :ol3_vector_styles
  resources :vector_features

  root 'welcome#index'
  get 'welcome/write_project_markdown' => 'welcome#write_project_markdown'
  resources :theme_map_layers
  resources :map_layers
  
  resources :theme_maps do
    get 'revert_geo_db', on: :member
    post 'update_geo_db', on: :member
    post 'delete_feature', on: :member
  end

  resources :theme_maps
  get 'theme_maps/:name' => 'theme_maps#show'

  resources :forums
  resources :wiki
  resources :about
  resources :guide
  resources :welcome 
  resources :administrators  
  
  

  resources :walk_surveys
  resources :overall_map
  resources :half_blocks
  resources :neighbors
  resources :greenwood_users
  resources :maps

  get '/logout' =>  'sessions#destroy'
  get '/login' => 'sessions#new'
  get '/register'=> 'users#create'
  get '/signup' => 'users#new'
  get '/activate/:activation_code' =>  'users#activate', :activation_code => nil

  resources :users
  resource :session
  resources :passwords
  resources :users

  get '/change_password' => 'users#change_password'
  get  '/neighbors/:search_column/:match_list' => 'neighbors#index'

end

app/models/neighbor.rb
# require 'spatial_adapter/postgresql'

class Neighbor < ActiveRecord::Base

  belongs_to :users  # foreign_key = neighbor_id

  serialize :why_walk, Array
  serialize :dont_walk, Array
  serialize :improvements, Array
  serialize :volunteer, Array

  def get_address_string
    address_string = self.address.gsub(/\s/, '+')
    address_string += ',Seattle,WA' 
    address_string.chomp!
    return address_string
  end

  def get_half_block_id
    sql = "SELECT DISTINCT b.half_block_id FROM half_blocks AS b, neighbors AS n  WHERE n.id = '#{self.id}' AND ST_Contains(b.the_geom,n.location)"
    half_block = HalfBlock.find_by_sql(sql)[0]
    if half_block
      half_block_id = half_block.half_block_id
      return half_block_id
    else
      return 'outside project area'
    end

  end
end

app/controllers/neighbors_controller.rb
require 'rubygems'
require 'curl'
require 'json'
require 'proj4'
# before_filter :login_required


class NeighborsController < ApplicationController
  # !!! require_role "admin", :only => :index # only admin gets to see all the neighbors

  def to_yaml
    @neighbors = Neighbor.all
    today = Date.today
    file = File.new('neighbors_latest.yml' + today, 'w')
    @neighbors.each do |n|
      yaml_string = ya2yaml(n)
      file.puts yaml_string
    end
  end


  def index  # accessible only to users with role 'admin'
    # returns a list of neighbors satisfying the passed database search query
    # returns 'no_matches_found' when this is so
    # params :search_column
    # params :match_list
    # params :order_by
    @neighbors = nil
    if params[:search_column]
      if params[:order_by]
        @neighbors = Neighbor.where(params[:search_column] => params[:match_list].split)
      else
        @neighbors = Neighbor.where(params[:search_column] => params[:match_list].split)
      end
    else # no params
      @neighbors = Neighbor.all
    end
  end


  def show
    @neighbor = Neighbor.find(params[:id])
    get_block_id
  end


  def new
    @neighbor = Neighbor.new
    @neighbor.volunteer = []
    @neighbor.improvements = []
    @neighbor.why_walk = []
    @neighbor.dont_walk = []
    @volunteer = []
    @improvements = []
    @why_walk = []
    @dont_walk = []
  end


  def edit
    @neighbor = Neighbor.find(params[:id])
    logger.debug @neighbor.inspect
    if @neighbor.improvements == nil
      @neighbor.improvements = []
    end
    if @neighbor.volunteer == nil
      @neighbor.volunteer = []
    end
    if @neighbor.why_walk == nil
      @neighbor.why_walk = []
    end
    if @neighbor.dont_walk == nil
      @neighbor.dont_walk = []
    end
  end


  def create
    @neighbor = Neighbor.new(params[:neighbor])
    @neighbor.improvements = params[:improvements]
    @neighbor.volunteer = params[:volunteer]
    @neighbor.why_walk = params[:why_walk]
    @neighbor.dont_walk = params[:dont_walk]
    if @neighbor.save
      flash[:notice] = 'Neighbor was successfully created.'
      redirect_to(@neighbor)
    else
      render  "new"
    end
  end


  def update
    @neighbor = Neighbor.find(params[:id])
    @neighbor.improvements = params[:improvements]
    @neighbor.volunteer = params[:volunteer]
    @neighbor.why_walk = params[:why_walk]
    @neighbor.dont_walk = params[:dont_walk]

    #if @neighbor.half_block_id == ''
    get_block_id
    #@neighbor.save
    #end

    if @neighbor.update_attributes(params[:neighbor])
      flash[:notice] = 'Neighbor was successfully updated.'
      redirect_to(@neighbor)
    else
      render "edit"
    end
  end


  def destroy
    @neighbor = Neighbor.find(params[:id])
    @neighbor.destroy
    redirect_to(neighbors_url)
  end


  protected


  def get_block_id
    if @neighbor.address == '' or @neighbor.address == nil
      return
    else
      @address_string = @neighbor.get_address_string
      geoJson= Curl::Easy.perform("http://maps.google.com/maps/api/geocode/json?address=#{@address_string}&sensor=false")
      json = geoJson.body_str
      parsed_json = JSON.parse(json)
      results = parsed_json.fetch 'results'
      lat = results[0]["geometry"]["location"]["lat"].to_f
      lon = results[0]["geometry"]["location"]["lng"].to_f

      srcPoint = Proj4::Point.new(Math::PI * lon / 180, Math::PI * lat / 180)
      destPrj = Proj4::Projection.new("+proj=lcc +lat_1=47.5 +lat_2=48.73333333333333 +lat_0=47 +lon_0=-120.8333333333333 +x_0=500000.0000000002 +y_0=0 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs")
      point = destPrj.forward(srcPoint)
      @neighbor.location = Point.from_x_y(point.x, point.y, 4326)
      half_block_id = @neighbor.get_half_block_id
      @neighbor.half_block_id = half_block_id
      @neighbor.save
    end
  end
end

app/views/neighbors/edit.html.erb
<br />
<h3>Edit or update your information:</h3>


<% form_for(@neighbor) do |f| %>



  <p>
    <%= f.label 'Street Address' %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label 'Unit / Apartment #' %><br />
    <%= f.text_field :unit %>
  </p>
  <p>
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </p>
	<h3> Occupant 1 </h3>
	<p>
    <%= f.label 'First Name'%><br />
    <%= f.text_field :first_name1 %>
  </p>
  <p>
    <%= f.label 'Last Name' %><br />
    <%= f.text_field :last_name1 %>
  </p>
  <p>
    <%= f.label 'Phone' %><br />
    <%= f.text_field :phone_1 %>
  </p>
   <p>
    <%= f.label "Email" %><br />
    <%= f.text_field :email_1 %>
  </p>
	<h3> Occupant 2 </h3>
  <p>
    <%= f.label 'First Name'%><br />
    <%= f.text_field :first_name2 %>
  </p>
   <p>
    <%= f.label 'Last Name'%><br />
    <%= f.text_field :last_name2 %>
  </p>
  <p>
    <%= f.label 'Phone' %><br />
    <%= f.text_field :phone_2%>
  </p>
   <p>
    <%= f.label "Email" %><br />
    <%= f.text_field :email_2 %>
  </p>


<div class="green">     
<h4  > Resident? </h4>
     <%= radio_button("neighbor", "resident", "resident") %> Resident
     <%= radio_button("neighbor", "resident", "business")  %> Business Owner
     <%= radio_button("neighbor", "resident", "both") %> Both
     <%= radio_button("neighbor", "resident", "neither") %> Neither
		 
<br />    
</div>

   <p>
    <%= f.label "How many years have you lived in Greenwood?" %>
    <%= f.text_field :years, :size => 4 %>
  </p>
   
<div class="green">     
<h4 >Interested in being a Block Facilitator? </h4>
     <%= radio_button("neighbor", "block_captain", "yes") %> yes
     <%= radio_button("neighbor", "block_captain", "no")  %> no
     <%= radio_button("neighbor", "block_captain", "maybe") %>  maybe
<br />    
</div>


<div class="blue">   
<h4 >Interested in volunteering?</h4>
<table>  
   		<tr><td><%= check_box_tag 'volunteer[]', '_non-skilled', @neighbor.volunteer.index("_non-skilled") %> I'll Do Whatever!</td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_LA', @neighbor.volunteer.index("_LA") %> Landscape Architect </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_civil', @neighbor.volunteer.index("_civil") %> Civil Engineer </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_writer', @neighbor.volunteer.index("_writer") %> Writer / Editor </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_graphic', @neighbor.volunteer.index("_graphic") %> Graphic Designer </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_gardening', @neighbor.volunteer.index("_gardening") %> Gardening </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_construction', @neighbor.volunteer.index("_construction") %> Construction </td></tr>			
</table>
</div>

<div class="green">     
<h4 >Do you want sidewalks / walkways built on your block?</h4>
     <%= radio_button("neighbor", "sidewalks", "yes") %> yes
     <%= radio_button("neighbor", "sidewalks", "have") %> we already have sidewalks
     <%= radio_button("neighbor", "sidewalks", "no")  %> no, I don't want sidewalks
     <%= radio_button("neighbor", "sidewalks", "maybe") %>  maybe / I'm not sure
		 
		 
<br />    
</div>


<div class="blue">   
<h4 >What other types of improvements would you like to see on your block? (check all that apply)</h4>
<table>  
   		<tr><td><%= check_box_tag 'improvements[]', '_none', @neighbor.improvements.index("_none") %> None </td></tr>
      <tr><td><%= check_box_tag 'improvements[]', '_trees', @neighbor.improvements.index("_trees") %> Street Trees / Plants </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_plants', @neighbor.improvements.index("_plants") %> Vegetable Gardens (Agriculture) </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_curbs', @neighbor.improvements.index("_curbs") %> Curbs </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_slow', @neighbor.improvements.index("_slow") %> Traffic Calming Measures (slow traffic, reduce collisions!) </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_rain', @neighbor.improvements.index("_rain") %> Rain Gardens (put rain in garden, not the storm sewer!) </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_gather', @neighbor.improvements.index("_gather") %> Seating / Picnic Table / Small Gathering Space somewhere on your block</td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_play', @neighbor.improvements.index("_play") %> Play Area </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_parking', @neighbor.improvements.index("_parking") %> Parking Improvements </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_crosswalk', @neighbor.improvements.index("_crosswalk") %> Intersection / Crosswalk Improvements </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_lighting', @neighbor.improvements.index("_lighting") %> Lighting Improvements </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_drain', @neighbor.improvements.index("_drain") %> Drainage Improvements  </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_ditch', @neighbor.improvements.index("_ditch") %> Drainage Ditch Improvements  </td></tr>
			
</table>
</div>

<div class="blue">   
<h4 >Why Do You Walk in Greenwood?</h4>
<table>  
   		<tr><td><%= check_box_tag 'why_walk[]', '_school', @neighbor.why_walk.index("_school") %> School </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_daycare', @neighbor.why_walk.index("_daycare") %> Daycare </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_visit', @neighbor.why_walk.index("_visit") %> Visit Friends / Family </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_trans', @neighbor.why_walk.index("_trans") %> Get to Public Transportation </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_parks', @neighbor.why_walk.index("_parks") %> Parks </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_dog', @neighbor.why_walk.index("_dog") %> Walk My Dog </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_work', @neighbor.why_walk.index("_work") %> Get to Work </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_shop', @neighbor.why_walk.index("_shop") %> Shopping / take care of business </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_exercise', @neighbor.why_walk.index("_exercise") %> Exercise </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_fun', @neighbor.why_walk.index("_fun") %> For Fun </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_social', @neighbor.why_walk.index("_social") %> Social Interaction</td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_meet', @neighbor.why_walk.index("_meet") %> Meet My Neighbors </td></tr>

</table>
</div>

<div class="blue">   
<h4 >Why DON'T You Walk in Greenwood?</h4>
<table>  
   		<tr><td><%= check_box_tag 'dont_walk[]', '_time', @neighbor.dont_walk.index("_time") %> Takes Too Long </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_weather', @neighbor.dont_walk.index("_weather") %> Weather </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_health', @neighbor.dont_walk.index("_health") %> Health Issues Prohibit </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_traffic', @neighbor.dont_walk.index("_traffic") %> Roads Too Busy </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_nothing', @neighbor.dont_walk.index("_nothing") %> Nothing of Interest Nearby </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_dislike', @neighbor.dont_walk.index("_dislike") %> Don't Want to Walk </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_hills', @neighbor.dont_walk.index("_hills") %> Too Many Hills </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_safety', @neighbor.dont_walk.index("_safety") %> I Don't feel safe / No Sidewalks </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_light', @neighbor.dont_walk.index("_light") %> Poor Lighting </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_other', @neighbor.dont_walk.index("_other") %> Other </td></tr>

</table>
</div>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<!-- <%= link_to 'Show', @neighbor %> |     -->
<!-- <%= link_to 'Back', neighbors_path %>  -->

app/views/neighbors/index.html.erb
<div class='left_margin'>

<h1>Listing neighbors</h1>
<br /><br />
<%= link_to "add these neighbors to current send-to list" ,{},  { :class => 'to_do', :title => 'create or add to the current list of email recipients' } %>
<br /><br />

<table class='left_margin' >
  <tr>
    <th>First Name </th>
    <th>Last Name </th>

    <th>Address - -</th>
    <th>Block ID</th>
    <th>Phone Number - - - </th>
    <th>Email Address - - - - - -</th>

    <th>Facilitator?</th>
  </tr>

<% @neighbors.each do |neighbor| %>
  <tr>
    <td>&nbsp;<%=h neighbor.first_name1 %></td>
    <td>&nbsp;<%=h neighbor.last_name1 %></td>

    <td>&nbsp;<%=h neighbor.address %></td>
    <td>&nbsp;&nbsp;<%=h neighbor.half_block_id %></td>
    <td>&nbsp;<%=h neighbor.phone_1 %></td>
    <td>&nbsp;<%=h neighbor.email_1 %></td>

    <td>&nbsp;<%=h neighbor.block_captain %></td>

    <td><%= link_to 'Show', neighbor %></td>
    <td><%= link_to 'Edit', edit_neighbor_path(neighbor) %></td>
    <td><%= link_to 'Destroy', neighbor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />


</div>

app/views/neighbors/new.html.erb
<div class="blue">
	<br />
<h3>Please fill out the questionnaire below to help us serve you. </h3>
<h3>(Don't forget to hit the 'SAVE' button at the bottom of the page!)</h3>
<br />



<% form_for(@neighbor) do |f| %>
  <%= f.error_messages %>


  <p>
    <%= f.label 'Street Address' %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label 'Unit / Apartment #' %><br />
    <%= f.text_field :unit %>
  </p>
  <p>
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </p>
	<h3> Occupant 1 </h3>
	<p>
    <%= f.label 'First Name'%><br />
    <%= f.text_field :first_name1 %>
  </p>
  <p>
    <%= f.label 'Last Name' %><br />
    <%= f.text_field :last_name1 %>
  </p>
  <p>
    <%= f.label 'Phone' %><br />
    <%= f.text_field :phone_1 %>
  </p>
   <p>
    <%= f.label "Email" %><br />
    <%= f.text_field :email_1 %>
  </p>
	<h3> Occupant 2 </h3>
  <p>
    <%= f.label 'First Name'%><br />
    <%= f.text_field :first_name2 %>
  </p>
   <p>
    <%= f.label 'Last Name'%><br />
    <%= f.text_field :last_name2 %>
  </p>
  <p>
    <%= f.label 'Phone' %><br />
    <%= f.text_field :phone_2%>
  </p>
   <p>
    <%= f.label "Email" %><br />
    <%= f.text_field :email_2 %>
  </p>



<div class="green">     
<h4  > Resident? </h4>
     <%= radio_button("neighbor", "resident", "resident") %> Resident
     <%= radio_button("neighbor", "resident", "business")  %> Business Owner
     <%= radio_button("neighbor", "resident", "both") %> Both
     <%= radio_button("neighbor", "resident", "neither") %> Neither
		 
<br />    
</div>


   <p>
    <%= f.label "How many years have you lived in Greenwood?" %><br />
    <%= f.text_field :years , :size => 4 %>
  </p>



<div class="green">     
<h4 >Interested in being a Block Facilitator? </h4>
     <%= radio_button("neighbor", "block_captain", "yes") %> yes
     <%= radio_button("neighbor", "block_captain", "no")  %> no
     <%= radio_button("neighbor", "block_captain", "maybe") %>  maybe
<br />    
</div>

<div class="blue">   
<h4 >Interested in volunteering?</h4>
<table>  
   		<tr><td><%= check_box_tag 'volunteer[]', '_non-skilled', @neighbor.volunteer.index("_non-skilled") %> I'll Do Whatever!</td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_LA', @neighbor.volunteer.index("_LA") %> Landscape Architect </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_civil', @neighbor.volunteer.index("_civil") %> Civil Engineer </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_writer', @neighbor.volunteer.index("_writer") %> Writer / Editor </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_graphic', @neighbor.volunteer.index("_graphic") %> Graphic Designer </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_gardening', @neighbor.volunteer.index("_gardening") %> Gardening </td></tr>
     	<tr><td><%= check_box_tag 'volunteer[]', '_construction', @neighbor.volunteer.index("_construction") %> Construction </td></tr>			
</table>
</div>

<div class="green">     
<h4 >Do you want sidewalks / walkways built on your block?</h4>
     <%= radio_button("neighbor", "sidewalks", "yes") %> yes
     <%= radio_button("neighbor", "sidewalks", "have") %> we already have sidewalks
     <%= radio_button("neighbor", "sidewalks", "no")  %> no, I don't want sidewalks
     <%= radio_button("neighbor", "sidewalks", "maybe") %>  maybe / I'm not sure
		 
		 
<br />    
</div>


<div class="blue">   
<h4 >What other types of improvements would you like to see on your block? (check all that apply)</h4>
<table>  
   		<tr><td><%= check_box_tag 'improvements[]', '_none', @neighbor.improvements.index("_none") %> None </td></tr>
      <tr><td><%= check_box_tag 'improvements[]', '_trees', @neighbor.improvements.index("_trees") %> Street Trees / Plants </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_plants', @neighbor.improvements.index("_plants") %> Vegetable Gardens (Agriculture) </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_curbs', @neighbor.improvements.index("_curbs") %> Curbs </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_slow', @neighbor.improvements.index("_slow") %> Traffic Calming Measures (slow traffic, reduce collisions!) </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_rain', @neighbor.improvements.index("_rain") %> Rain Gardens (put rain in garden, not the storm sewer!) </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_gather', @neighbor.improvements.index("_gather") %> Seating / Picnic Table / Small Gathering Space somewhere on your block</td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_play', @neighbor.improvements.index("_play") %> Play Area </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_parking', @neighbor.improvements.index("_parking") %> Parking Improvements </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_crosswalk', @neighbor.improvements.index("_crosswalk") %> Intersection / Crosswalk Improvements </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_lighting', @neighbor.improvements.index("_lighting") %> Lighting Improvements </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_drain', @neighbor.improvements.index("_drain") %> Drainage Improvements  </td></tr>
     	<tr><td><%= check_box_tag 'improvements[]', '_ditch', @neighbor.improvements.index("_ditch") %> Drainage Ditch Improvements  </td></tr>
			
</table>
</div>

<div class="blue">   
<h4 >Why Do You Walk in Greenwood?</h4>
<table>  
   		<tr><td><%= check_box_tag 'why_walk[]', '_school', @neighbor.why_walk.index("_school") %> School </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_daycare', @neighbor.why_walk.index("_daycare") %> Daycare </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_visit', @neighbor.why_walk.index("_visit") %> Visit Friends / Family </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_trans', @neighbor.why_walk.index("_trans") %> Get to Public Transportation </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_parks', @neighbor.why_walk.index("_parks") %> Parks </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_dog', @neighbor.why_walk.index("_dog") %> Walk My Dog </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_work', @neighbor.why_walk.index("_work") %> Get to Work </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_shop', @neighbor.why_walk.index("_shop") %> Shopping / take care of business </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_exercise', @neighbor.why_walk.index("_exercise") %> Exercise </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_fun', @neighbor.why_walk.index("_fun") %> For Fun </td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_social', @neighbor.why_walk.index("_social") %> Social Interaction</td></tr>
   		<tr><td><%= check_box_tag 'why_walk[]', '_meet', @neighbor.why_walk.index("_meet") %> Meet My Neighbors </td></tr>

</table>
</div>

<div class="blue">   
<h4 >Why DON'T You Walk in Greenwood?</h4>
<table>  
   		<tr><td><%= check_box_tag 'dont_walk[]', '_time', @neighbor.dont_walk.index("_time") %> Takes Too Long </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_weather', @neighbor.dont_walk.index("_weather") %> Weather </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_health', @neighbor.dont_walk.index("_health") %> Health Issues Prohibit </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_traffic', @neighbor.dont_walk.index("_traffic") %> Roads Too Busy </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_nothing', @neighbor.dont_walk.index("_nothing") %> Nothing of Interest Nearby </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_dislike', @neighbor.dont_walk.index("_dislike") %> Don't Want to Walk </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_hills', @neighbor.dont_walk.index("_hills") %> Too Many Hills </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_safety', @neighbor.dont_walk.index("_safety") %> I Don't feel safe / No Sidewalks </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_light', @neighbor.dont_walk.index("_light") %> Poor Lighting </td></tr>
   		<tr><td><%= check_box_tag 'dont_walk[]', '_other', @neighbor.dont_walk.index("_other") %> Other </td></tr>

</table>
</div>


  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', neighbors_path %>