config/routes.rb
NeighborsMaps::Application.routes.draw do
  resources :ol3_vector_styles
  resources :vector_features

  root 'welcome#index'
  get 'welcome/write_project_markdown' => 'welcome#write_project_markdown'
  resources :theme_map_layers
  resources :map_layers
  
  resources :theme_maps do
    get 'revert_geo_db', on: :member
    post 'update_geo_db', on: :member
    post 'delete_feature', on: :member
  end

  resources :theme_maps
  get 'theme_maps/:name' => 'theme_maps#show'

  resources :forums
  resources :wiki
  resources :about
  resources :guide
  resources :welcome 
  resources :administrators  
  
  

  resources :walk_surveys
  resources :overall_map
  resources :half_blocks
  resources :neighbors
  resources :greenwood_users
  resources :maps

  get '/logout' =>  'sessions#destroy'
  get '/login' => 'sessions#new'
  get '/register'=> 'users#create'
  get '/signup' => 'users#new'
  get '/activate/:activation_code' =>  'users#activate', :activation_code => nil

  resources :users
  resource :session
  resources :passwords
  resources :users

  get '/change_password' => 'users#change_password'
  get  '/neighbors/:search_column/:match_list' => 'neighbors#index'

end

app/models/vector_feature.rb
require 'rgeo/geo_json'

class VectorFeature < ActiveRecord::Base


  include ActionView::Helpers::OutputSafetyHelper

  belongs_to :map_layer
  belongs_to :user
  
  # load all vector_features on map_layer, or only those of current user...
  def self.load_geo_json(map_layer_id, only_current_user = false) 
    current_user_sql = ""
    if only_current_user == true
      current_user_sql = "user_id = #{current_user.id} AND "
    end
    query = <<-SQL
      SELECT row_to_json(fc)
        FROM ( SELECT 'FeatureCollection' As type, array_to_json(array_agg(f)) As features
        FROM ( SELECT 'Feature' As type
      , ST_AsGeoJSON(lg.geometry)::json As geometry
      , lg.id AS id
      , row_to_json((SELECT l FROM (SELECT id, value, text, number, amount) As l
        )) As properties
        FROM ( SELECT * FROM vector_features 
        WHERE #{ current_user_sql } map_layer_id = #{map_layer_id}) As lg ) As f ) As fc;
    SQL
     result = ActiveRecord::Base.connection.execute(query)
     tj= JSON.parse(result[0]["row_to_json"])
     if tj["features"] == nil
       return "'none'"
     else
       return result[0]["row_to_json"]
     end
  end


  def as_geo_json
    query = <<-SQL
       SELECT row_to_json(fc)
        FROM ( SELECT 'FeatureCollection' As type, array_to_json(array_agg(f)) As features
        FROM ( SELECT 'Feature' As type
      , ST_AsGeoJSON(lg.geometry)::json As geometry
      , lg.id AS id
      , row_to_json((SELECT l FROM (SELECT id, value, text, number, amount) As l
        )) As properties
        FROM ( SELECT * FROM vector_features 
        WHERE id = #{self.id}) As lg ) As f ) As fc;
    SQL
     
  end


  def self.test_features
     json = <<-FEATURES
    {"type": "FeatureCollection", "features": [{ "type": "Feature","geometry": { "type": "LineString", "coordinates": [[-13621522.730645318, 6055608.910350661],[ -13621083.217732677, 6055284.052980449], [ -13620165.973393254, 6055312.7168660555], [-13619841.116023043, 6055112.069666808], [ -13619119.496548858, 6055252.217636055]] }, "properties": { "id": 333,  "value": "my_path_1", "text": "This is where I like to go when I take a walk.", "number":"5"} },
    { "type": "Feature","geometry": { "type": "LineString", "coordinates": [[-13621589.613045067, 6056440.163033262],[ -13621446.29361703, 6056745.911146402], [ -13619602.250309652, 6056487.936175941],[ -13619153.182768477, 6056573.927832761]] },"properties": { "id": 757,  "value": "my_path_2", "text": "walking to grocery store", "number":"2"}} ]}
FEATURES
  end


  def from_json(json)
    jp = JSON.parse json
    f = jp["features"][0]
    feature = RGeo::GeoJSON.decode( json, json_parser: :json )[1]
    wkt_string  = feature.geometry.as_text
    g_factory = RGeo::Cartesian::Factory.new(srid: 3857)
    self.geometry = g_factory.parse_wkt(wkt_string)
      
  end

  def self.to_mercator(geom)
    proj4_2926 = '+proj=lcc +lat_1=48.73333333333333 +lat_2=47.5 +lat_0=47 +lon_0=-120.8333333333333 +x_0=500000.0001016001' +
                  ' +y_0=0 +ellps=GRS80 +to_meter=0.3048006096012192 +no_defs'

    wkt_2926 = <<-WKT
              'PROJCS["NAD83(HARN) / Washington North (ftUS)",GEOGCS["NAD83(HARN)",
                DATUM["NAD83_High_Accuracy_Regional_Network",SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6152"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],
                UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4152"]],
                UNIT["US survey foot",0.3048006096012192,AUTHORITY["EPSG","9003"]],
                PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",48.73333333333333],
                PARAMETER["standard_parallel_2",47.5],PARAMETER["latitude_of_origin",47],PARAMETER["central_meridian",
                -120.8333333333333],PARAMETER["false_easting",1640416.667],PARAMETER["false_northing",0],
                AUTHORITY["EPSG","2926"],AXIS["X",EAST],AXIS["Y",NORTH]]'
                WKT

    proj4_3857 = '+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'

    wkt_3857 = <<-WKT
               'PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["Popular Visualisation CRS",DATUM["Popular_Visualisation_Datum",
               SPHEROID["Popular Visualisation Sphere",6378137,0,AUTHORITY["EPSG","7059"]],TOWGS84[0,0,0,0,0,0,0],
               AUTHORITY["EPSG","6055"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],
               UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4055"]],
               UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Mercator_1SP"],
               PARAMETER["central_meridian",0],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],
               PARAMETER["false_northing",0],AUTHORITY["EPSG","3785"],AXIS["X",EAST],AXIS["Y",NORTH]]'
               WKT

    factory_2926 = RGeo::Cartesian.factory(:srid => 2926, :proj4 => proj4_2926, :coord_sys => wkt_2926)
    factory_3857 = RGeo::Cartesian.factory(:srid => 3875, :proj4 => proj4_3857, :coord_sys => wkt_3857)
    temp_geom = RGeo::Feature.cast(geom, factory: factory_2926, project: false)
    new_geom = RGeo::Feature.cast(temp_geom, factory: factory_3857, project: true)
  end

  def self.to_vector_feature(neighbor)
    vf = VectorFeature.new
    vf.user_id = neighbor.user_id
    vf.map_layer_id = 33
    vf.value = neighbor.last_name1
    vf.geometry = VectorFeature::to_mercator neighbor.location
    vf.save
  end

end

app/controllers/vector_features_controller.rb
class VectorFeaturesController < ApplicationController
  before_action :set_vector_feature, only: [:show, :edit, :update, :destroy]

  # GET /vector_features
  # GET /vector_features.json
  def index
    @vector_features = VectorFeature.all
  end

  # GET /vector_features/1
  # GET /vector_features/1.json
  def show
  end

  # GET /vector_features/new
  def new
    @vector_feature = VectorFeature.new
  end

  # GET /vector_features/1/edit
  def edit
  end

  # POST /vector_features
  # POST /vector_features.json
  def create
    @vector_feature = VectorFeature.new(vector_feature_params)

    respond_to do |format|
      if @vector_feature.save
        format.html { redirect_to @vector_feature, notice: 'Vector feature was successfully created.' }
        format.json { render :show, status: :created, location: @vector_feature }
      else
        format.html { render :new }
        format.json { render json: @vector_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vector_features/1
  # PATCH/PUT /vector_features/1.json
  def update
    respond_to do |format|
      if @vector_feature.update(vector_feature_params)
        format.html { redirect_to @vector_feature, notice: 'Vector feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @vector_feature }
      else
        format.html { render :edit }
        format.json { render json: @vector_feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vector_features/1
  # DELETE /vector_features/1.json
  def destroy
    @vector_feature.destroy
    respond_to do |format|
      format.html { redirect_to vector_features_url, notice: 'Vector feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vector_feature
      @vector_feature = VectorFeature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vector_feature_params
      params.require(:vector_feature).permit(:name, :text, :vector_type, :amount, :number, :guid)
    end
end

app/views/vector_features/_form.html.erb
<%= form_for(@vector_feature) do |f| %>
  <% if @vector_feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vector_feature.errors.count, "error") %> prohibited this vector_feature from being saved:</h2>

      <ul>
      <% @vector_feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :vector_type %><br>
    <%= f.text_field :vector_type %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :guid %><br>
    <%= f.text_field :guid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vector_features/edit.html.erb
<h1>Editing Vector Feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @vector_feature %> |
<%= link_to 'Back', vector_features_path %>

app/views/vector_features/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vector Features</h1>

<table class="pretty-grid">
  <thead>
    <tr>
      <th>Map Layer Name</th>
      <th>Value</th>
      <th>Text</th>
      <th>Vector type</th>
      <th>Amount</th>
      <th>Number</th>
      <th>Guid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vector_features.each do |vector_feature| %>
      <tr>
        <td><%= vector_feature.map_layer.name %></td>
        <td><%= vector_feature.value %></td>
        <td><%= vector_feature.text %></td>
        <td><%= vector_feature.vector_type %></td>
        <td><%= vector_feature.amount %></td>
        <td><%= vector_feature.number %></td>
        <td><%= vector_feature.guid %></td>
        <td><%= vector_feature.geometry.as_text %></td>
        <td><%= link_to 'Show', vector_feature %></td>
        <td><%= link_to 'Edit', edit_vector_feature_path(vector_feature) %></td>
        <td><%= link_to 'Destroy', vector_feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vector feature', new_vector_feature_path %>

app/views/vector_features/new.html.erb
<h1>New Vector Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', vector_features_path %>

app/views/vector_features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vector_feature.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @vector_feature.text %>
</p>

<p>
  <strong>Vector type:</strong>
  <%= @vector_feature.vector_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @vector_feature.amount %>
</p>

<p>
  <strong>Number:</strong>
  <%= @vector_feature.number %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @vector_feature.guid %>
</p>

<%= link_to 'Edit', edit_vector_feature_path(@vector_feature) %> |
<%= link_to 'Back', vector_features_path %>